### ISSUE TITLE
Add GDG Vilnius logo

### ISSUE THREAD

**Issue by AlexeyBuzdin** [gdgriga/hoverboard#21]
```
  <iron-image
          class="gdg-logo"
          src="/images/gdg-logo.svg"
          sizing="contain"
          alt="{$ organizer.name $}"
        ></iron-image>
```

in `src/elements/footer-block.html` should be a list of `.svg` for each GDG with clickable links

**Comment by skibish** [comment]
We will add them to organizers block when we will open it @AlexeyBuzdin

**Comment by AlexeyBuzdin** [comment]
Let's add them there as well for PR, with potentially Tartu and Kaunas. Person scrolls to bottom and sees that it's a collaboration of GDGs

**Comment by skibish** [comment]
organizers block will be at the bottom. Second block is footer

**Comment by skibish** [comment]
https://github.com/gdgriga/hoverboard/blob/dev/src/pages/home-page.html#L88-L93
