### ISSUE TITLE
Заменить цвета

### ISSUE THREAD

**Issue by imeugenia** [gdgriga/hoverboard#3]
Фиолетовый: 651fff, 
тёмно-фиолетовый: 311b92, 
светло-красный: ff8a80
белый: ffffff

Какой фон у какого блока:
1. Header - на фоне будет иллюстрация, где будет преобладать фиолетовый
2. About - светло-красный
3. Speakers - белый
4. Tickets - тёмно-фиолетовый (цвет текста изменить на белый)
5. Partners - белый
6. Footer - оставить пока что серым

**Comment by skibish** [comment]
Это я отдаю тебе, сможешь поиграться с настройками :)

В основном настройки по **основным** цветам в: `src/styles/shared-styles.html`

Еще дофига тут: `data/hoverboard.config.json`

**Comment by skibish** [comment]
pull request #11
